---
- hosts: localhost
  connection: local
  tasks:
    - name: nodejs - add repository key
      apt_key:
        url: "{{ item }}"
      with_items:
        - "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        - "https://dl.yarnpkg.com/debian/pubkey.gpg"

    - name: nodejs - add repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: no
      with_items:
        - "deb https://deb.nodesource.com/setup_14.x {{ ansible_lsb.codename }} main"
        #- "deb http://deb.nodesource.com/node_10.x {{ ansible_lsb.codename }} main"
        #- "deb-src http://deb.nodesource.com/node_10.x {{ ansible_lsb.codename }} main"
        #- "deb https://dl.yarnpkg.com/debian/ stable main"

    - name: nodejs - install
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "nodejs"
        - "yarn"        

 