---
- name: Adding Jenkins repository
  yum_repository:
    name: Jenkins-stable
    description: Jenkins YUM repository
    baseurl: "http://pkg.jenkins.io/redhat-stable"
    gpgkey: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    gpgcheck: yes
  tags: jenkins

- name: Adding GPG key
  rpm_key:
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    state: present
  tags: jenkins

- name: Installing Jenkins
  yum:
    name: jenkins
    state: present
  tags: jenkins

- name: Starting and enabling Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
  tags: jenkins