---
- name: Copying network configuration file
  template:
    src: "{{ role_path }}/templates/etc/sysconfig/network-scripts/ifcfg-eth1.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
  tags: common

- name: Restarting network service
  service:
    name: network
    state: restarted
  tags: common

- name: Disabling SELinux
  selinux:
    state: disabled
  tags: common

- name: Stopping and disabling firewall service
  service:
    name: firewalld
    state: stopped
    enabled: no
  tags: common

- name: Setting timezone to Etc/GMT
  timezone:
    name: Etc/GMT
  tags: common

- name: Addding EPEL repository
  yum:
    name: epel-release
    state: present
  tags: common

- name: Updating packages
  yum:
    name: '*'
    state: latest
  tags: common

- name: Installing necessary packages
  yum:
    name:
      - bind-utils
      - bzip2
      - curl
      - htop
      - iotop
      - lsof
      - nc
      - net-tools
      - nmap
      - p7zip
      - rsync
      - screen
      - sshpass
      - tcpdump
      - telnet
      - tree
      - unzip
      - vim
      - wget
      - yum-utils
      - zip
    state: present
  tags: common

- name: Setting up Vim for "root" user
  get_url:
    url: "https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim"
    dest: ~/.vimrc
  tags: common

- name: Setting up Vim for "vagrant" user
  become_user: vagrant
  get_url:
    url: "https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim"
    dest: ~/.vimrc
  tags: common

- name: Creating "app" user
  user:
    name: app
    password: "{{ '1rstwap' | password_hash('sha512') }}"
  tags: common

- name: Adding "app" user as sudoer
  copy:
    content: 'app ALL=(ALL) ALL'
    dest: /etc/sudoers.d/app
    mode: 0440
  tags: common

- name: Setting up Vim for "app" user
  become_user: app
  get_url:
    url: "https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim"
    dest: ~/.vimrc
  tags: common

- name: Creating "firstwap" user
  user:
    name: firstwap
    password: "{{ '1rstwap' | password_hash('sha512') }}"
  tags: common

- name: Adding "firstwap" user as sudoer
  copy:
    content: 'firstwap ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/firstwap
    mode: 0440
  tags: common

- name: Setting up Vim for "firstwap" user
  become_user: firstwap
  get_url:
    url: "https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim"
    dest: ~/.vimrc
  tags: common

- name: Copying user limit configuration file
  copy:
    src: "{{ role_path }}/files/etc/security/limits.conf"
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644
  tags: common

- name: Creating /archive directory
  file:
    path: /archive
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: common